name: Build and Push Containers
on:
  workflow_dispatch:

jobs:
  build-and-push-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

        ## This is needed for multi-architecutre builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io  # change this to github later?
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          # username: ${{ secrets.DOCKERHUB_USERNAME }}
          # password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and Push Containers
        id: buildx
        uses: docker/build-push-action@v4
        with:
          context: ./docker/auxiliary-containers/puppeteer # Change this to the path of your Dockerfiles directory
          push: true
          tags: |
            dan-mm/test-puppeteer:latest # Replace with your Docker Hub username and repository name
          platforms: linux/amd64,linux/arm64, darwin/amd64 # Add any other platforms you want to support
          builder: ${{ env.BUILDx_BUILDER }} # Optional, can speed up builds with a pre-built builder cache
