name: Build and Push Containers
on:
  pull_request:
    types:
      - closed
    paths:
      - 'docker/auxiliary-containers/**/Dockerfile'

  workflow_dispatch:

jobs:
  build-and-push-containers:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        ## This is needed for multi-architecture builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push auxiliary-containers
        shell: bash
        run: |
          PR_FILES=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" | jq -r '.[] | .filename')
          CHANGED_SUBFOLDERS=$(echo "$PR_FILES" | grep -E '^docker/auxiliary-containers/[^/]+/' | sed -r 's|^docker/auxiliary-containers/([^/]+)/.*|\1|' | sort -u)

          echo $CHANGED_SUBFOLDERS
          ./docker/build-containers.sh $CHANGED_SUBFOLDERS


        # ${{ github.run_number }} increments with each urn (stays the same if you re-run a failed/stalled job)
        # build-containers script takes the first arguement as the tag in the format: v1.x , where x is run_number
      # - name: Build and Push Containers
      #   shell: bash
      #   run: |
      #     # Get a list of all Dockerfiles that were modified in the PR
      #     CHANGED_DOCKERFILES=$(git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }} | grep 'docker/auxiliary-containers/.*Dockerfile$')

      #     # Extract the unique subfolders from the modified Dockerfile paths
      #     CHANGED_SUBFOLDERS=$(echo "$CHANGED_DOCKERFILES" | sed -n 's|^docker/auxiliary-containers/\(.*\)/[^/]*$|\1|p' | sort -u)

      #     echo "$CHANGED_SUBFOLDERS
