name: Sync Repositories

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository A
        uses: actions/checkout@v2
        
      - name: Checkout Repository B
        uses: actions/checkout@v2
        with:
          repository: dan-mm/test-repo-b
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
        
      - name: Merge dev branch into main (Repository B)
        run: |
          cd test-repo-b
          git merge origin/dev --no-edit
          
      - name: Push changes to Repository B
        run: |
          cd test-repo-b
          git push origin main
