name: Test Eco-CI Workflow

on:
  pull_request:
  workflow_dispatch:

# testing dependabot commit

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      pull-requests: write
    steps:      
      - name: Minimize Comment
        uses: green-coding-berlin/eco-ci-energy-estimation@minimize-old-comments
        with:
          task: test
          pr-comment: true
