name: Test Eco-CI Workflow

on:
  pull_request:
  workflow_dispatch:

# testing dependabot commit

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      pull-requests: write
    steps:      
      - name: Initialize energy estimation
        uses: green-coding-berlin/eco-ci-energy-estimation@minimize-old-comments
        with:
          task: start-measurement

      - name: Sleep
        run: sleep 4s
        shell: bash

      - name: Show Energy Results
        uses: green-coding-berlin/eco-ci-energy-estimation@minimize-old-comments
        with:
          task: display-results
          pr-comment: true
