
name: Test Eco-CI Workflow

on:
  workflow_dispatch:

# testing dependabot commit

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      pull-requests: write
    steps:      
      - name: Initialize energy estimation
        uses: green-coding-berlin/eco-ci-energy-estimation@main
        with:
          task: start-measurement

      - name: Sleep
        run: sleep 4s
        shell: bash

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1        

      - name: Show Energy Results
        uses: green-coding-berlin/eco-ci-energy-estimation@main
        with:
          task: display-results
